config/routes.rb
FreshpicksApi::Application.routes.draw do
  
  match 'today' => 'availabilities#today'
  match '', :to => redirect('/index.html'), :as => :root
  match '/', :to => redirect('/index.html'), :as => :root

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout
  match "/dish/:dish_id/availabilities/new" => "availabilities#new", :as => :newavailability

  resources :availabilities
  resources :dishes
  resources :chefs

end

app/models/chef.rb
class Chef < ActiveRecord::Base
  attr_accessible :bio, :location, :name, :rating, :specialty, :username
  has_many :dishes
  
  def as_json(options = {})
  	include_dishes = { :include => { :dishes => {} } }
  	
  	super(include_dishes.merge(options))
  end 
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  # GET /chefs
  # GET /chefs.json
  def index
    @chefs = Chef.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @chefs }
    end
  end

  # GET /chefs/1
  # GET /chefs/1.json
  def show
    @chef = Chef.find(params[:id])
    
    respond_to do |format|
      format.html { render :layout => 'clear_layout' } # show.html.erb
      format.json { render json: @chef }
    end
  end

  # GET /chefs/new
  # GET /chefs/new.json
  def new
    @chef = Chef.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @chef }
    end
  end

  # GET /chefs/1/edit
  def edit
    @chef = Chef.find(params[:id])
  end

  # POST /chefs
  # POST /chefs.json
  def create
    @chef = Chef.new(params[:chef])

    respond_to do |format|
      if @chef.save
        format.html { redirect_to @chef, notice: 'Chef was successfully created.' }
        format.json { render json: @chef, status: :created, location: @chef }
      else
        format.html { render action: "new" }
        format.json { render json: @chef.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /chefs/1
  # PUT /chefs/1.json
  def update
    @chef = Chef.find(params[:id])

    respond_to do |format|
      if @chef.update_attributes(params[:chef])
        format.html { redirect_to @chef, notice: 'Chef was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @chef.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chefs/1
  # DELETE /chefs/1.json
  def destroy
    @chef = Chef.find(params[:id])
    @chef.destroy

    respond_to do |format|
      format.html { redirect_to chefs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/chefs_helper.rb
module ChefsHelper
end

app/views/chefs/_form.html.erb
<%= form_for @chef, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :username, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :username, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :rating, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :rating, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :location, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :location, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :bio, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :bio, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :specialty, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :specialty, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                chefs_path, :class => 'btn' %>
  </div>
<% end %>

app/views/chefs/edit.html.erb
<%- model_class = Chef -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/chefs/index.html.erb
<%- model_class = Chef -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:username) %></th>
      <th><%= model_class.human_attribute_name(:rating) %></th>
      <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%= model_class.human_attribute_name(:bio) %></th>
      <th><%= model_class.human_attribute_name(:specialty) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @chefs.each do |chef| %>
      <tr>
        <td><%= link_to chef.id, chef_path(chef) %></td>
        <td><%= chef.name %></td>
        <td><%= chef.username %></td>
        <td><%= chef.rating %></td>
        <td><%= chef.location %></td>
        <td><%= chef.bio %></td>
        <td><%= chef.specialty %></td>
        <td><%=l chef.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_chef_path(chef), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      chef_path(chef),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_chef_path,
            :class => 'btn btn-primary' %>

app/views/chefs/new.html.erb
<%- model_class = Chef -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/chefs/show.html.erb
<%- model_class = Chef -%>

<div class="container-fluid">
<header class="row-fluid hdr">
      <div class="span4 header-l">
         <a href="#"><img src="/images/logo.png"/></a>
        </div>
        
        
        
        <div class="span8 header-r">
          <div class="dropdown pull-left">
         <div class="strong-txt img-drp">All San Francisco</div>
        </div>
      
          <div class="pagntn img-arw pull-right">
           <div class="strong-txt"> page 1 <span class="gray">of 5</span></div>
       
        </div>
        </div>
      
    </header>

<div class="row-fluid index">
  <div class="span4 single-thumb visible-desktop visible-tablet">
    <div class="thumbnail">
      <%= image_tag("/images/chefs/"+@chef.username+"/366C.jpg") %>
    </div>
    <h1><%= @chef.name %></h1>
    <h3><%= @chef.location %></h3>
    <h3><%= @chef.specialty %></h3>

    <div class="rating"><img src="/images/Untitled-4_35.png"/><b class="rating-txt">82 reviews</b> </div>
    <p class="detail"><%= @chef.bio %></p>
    
    <%= link_to "New Dish", "#", :class => 'btn btn-primary' %>

  </div>
    
    
  <div class="span4 single-thumb-mob visible-phone">
    <div class="thumbnail">
      <%= image_tag("/images/chefs/"+@chef.username+"/366C.jpg") %>
    </div>
    <h1><%= @chef.name %></h1>
    <h3><%= @chef.location %></h3>
	<h3><%= @chef.specialty %></h>
    <div class="rating"><img src="/images/Untitled-4_35.png"/><b class="rating-txt">82 reviews</b> </div>
    <p class="detail"><%= @chef.bio %></p>
    

    <%= link_to "New Dish", "#", :class => 'btn btn-primary' %>
  </div>
    
    
  <div class="span8">
   <div class="row-fluid">
	<% if @chef.dishes.any? %>
	    <ul class="thumbnails">
	    	<%= render @chef.dishes %>
     	</ul>
   <% end %>
</div>

  <footer class="span12">
    
  </footer>

</div>

<!--
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @chef.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:username) %>:</strong></dt>
  <dd><%= @chef.username %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rating) %>:</strong></dt>
  <dd><%= @chef.rating %></dd>
  <dt><strong><%= model_class.human_attribute_name(:location) %>:</strong></dt>
  <dd><%= @chef.location %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bio) %>:</strong></dt>
  <dd><%= @chef.bio %></dd>
  <dt><strong><%= model_class.human_attribute_name(:specialty) %>:</strong></dt>
  <dd><%= @chef.specialty %></dd>
</dl>
-->
<!--
<div class="row-fluid index">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              chefs_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_chef_path(@chef), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              chef_path(@chef),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>
-->
</div>