config/routes.rb
FreshpicksApi::Application.routes.draw do
  
  match 'today' => 'availabilities#today'
  match '', :to => redirect('/index.html'), :as => :root
  match '/', :to => redirect('/index.html'), :as => :root

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout
  match "/dish/:dish_id/availabilities/new" => "availabilities#new", :as => :newavailability

  resources :availabilities
  resources :dishes
  resources :chefs

end

app/models/dish.rb
class Dish < ActiveRecord::Base
  attr_accessible :cuisine, :desription, :diet_flags, :ingredients, :name, :price, :chef_id
  belongs_to :chef

  def as_json(options = {})
  	include_chef = { :include => { :chef => {} } }
  	
  	super(include_chef.merge(options))
  end 
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  load_and_authorize_resource

  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dishes }
    end
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dish }
    end
  end

  # GET /dishes/new
  # GET /dishes/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dish }
    end
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes
  # POST /dishes.json
  def create
    #@dish.chef = current_user.chef

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
        format.json { render json: @dish, status: :created, location: @dish }
      else
        format.html { render action: "new" }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dishes/1
  # PUT /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update_attributes(params[:dish])
        format.html { redirect_to @dish, notice: 'Dish was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish.destroy

    respond_to do |format|
      format.html { redirect_to dishes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_dish.html.erb
<li class="span4">
	<article class="thumbnail">
		<%= image_tag("/images/dishes/"+dish.id.to_s+"-200x200.jpg") %>
	</article>
	<div class="row-fluid thumb-desc">
		<div class="span8 description"><%= dish.name %></div>
		<div class="span4 price"><%= "$"+dish.price.to_i.to_s %></div>

		<%= link_to "Sell", "/dish/#{dish.id}/availabilities/new", :class => 'btn btn-primary' %>
	</div>
</li>

app/views/dishes/_form.html.erb
<%= form_for @dish, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :desription, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :desription, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :price, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :price, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :ingredients, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :ingredients, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :diet_flags, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :diet_flags, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :cuisine, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :cuisine, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :chef_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :chef_id, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                dishes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<%- model_class = Dish -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/dishes/index.html.erb
<%- model_class = Dish -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:desription) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:ingredients) %></th>
      <th><%= model_class.human_attribute_name(:diet_flags) %></th>
      <th><%= model_class.human_attribute_name(:cuisine) %></th>
      <th><%= model_class.human_attribute_name(:chef_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @dishes.each do |dish| %>
      <tr>
        <td><%= link_to dish.id, dish_path(dish) %></td>
        <td><%= dish.name %></td>
        <td><%= dish.desription %></td>
        <td><%= dish.price %></td>
        <td><%= dish.ingredients %></td>
        <td><%= dish.diet_flags %></td>
        <td><%= dish.cuisine %></td>
        <td><%= dish.chef_id %></td>
        <td><%=l dish.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_dish_path(dish), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      dish_path(dish),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_dish_path,
            :class => 'btn btn-primary' %>

app/views/dishes/new.html.erb
<%- model_class = Dish -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/dishes/show.html.erb
<%- model_class = Dish -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @dish.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:desription) %>:</strong></dt>
  <dd><%= @dish.desription %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @dish.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ingredients) %>:</strong></dt>
  <dd><%= @dish.ingredients %></dd>
  <dt><strong><%= model_class.human_attribute_name(:diet_flags) %>:</strong></dt>
  <dd><%= @dish.diet_flags %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cuisine) %>:</strong></dt>
  <dd><%= @dish.cuisine %></dd>
  <dt><strong><%= model_class.human_attribute_name(:chef_id) %>:</strong></dt>
  <dd><%= @dish.chef_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              dishes_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_dish_path(@dish), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              dish_path(@dish),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>