config/routes.rb
FreshpicksApi::Application.routes.draw do
  
  match 'today' => 'availabilities#today'
  match '', :to => redirect('/index.html'), :as => :root
  match '/', :to => redirect('/index.html'), :as => :root

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout
  match "/dish/:dish_id/availabilities/new" => "availabilities#new", :as => :newavailability

  resources :availabilities
  resources :dishes
  resources :chefs

end

app/models/availability.rb
class Availability < ActiveRecord::Base
  attr_accessible :expires_on, :starts_on, :initial_amount, :remaining_amount, :dish_id
  belongs_to :dish
  
  def as_json(options = {})
  	include_chefs = { :include => { :chef => {} } }
  	include_dish = { :include => { :dish => include_chefs } }
  	
  	super(include_dish.merge(options))
  end
end

app/controllers/availabilities_controller.rb
class AvailabilitiesController < ApplicationController
  # GET /availabilities
  # GET /availabilities.json
  def index
    @availabilities = Availability.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @availabilities }
    end
  end

  # GET /availabilities/1
  # GET /availabilities/1.json
  def show
    @availability = Availability.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @availability }
    end
  end

  def today
    @availabilities = Availability.where("expires_on >= ? and expires_on <= ?", Date.today, Date.tomorrow).order("created_at DESC")
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @availabilities }
    end
      
  end
  

  # GET /availabilities/new
  # GET /availabilities/new.json
  def new
    @availability = Availability.new
    @dish = Dish.find(params[:dish_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @availability }
    end
  end

  # GET /availabilities/1/edit
  def edit
    @availability = Availability.find(params[:id])
  end

  # POST /availabilities
  # POST /availabilities.json
  def create
    @availability = Availability.new(params[:availability])
    @availability.dish = Dish.find(params[:dish_id])
    
    @availability.remaining_amount = @availability.initial_amount
    @availability.expires_on = Date.today
    @availability.starts_on = Date.today

    respond_to do |format|
      if @availability.save
        format.html { redirect_to @availability.dish.chef, notice: 'Awesom.Go feed them!!!.' }
        format.json { render json: @availability, status: :created, location: @availability }
      else
        format.html { render action: "new" }
        format.json { render json: @availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /availabilities/1
  # PUT /availabilities/1.json
  def update
    @availability = Availability.find(params[:id])

    respond_to do |format|
      if @availability.update_attributes(params[:availability])
        format.html { redirect_to @availability, notice: 'Availability was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /day/2013-04-05.json
  def day

    
  end
  

  # DELETE /availabilities/1
  # DELETE /availabilities/1.json
  def destroy
    @availability = Availability.find(params[:id])
    @availability.destroy

    respond_to do |format|
      format.html { redirect_to availabilities_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/availabilities_helper.rb
module AvailabilitiesHelper
end

app/views/availabilities/_form.html.erb
<%= form_for @availability, :html => { :class => 'form-horizontal' } do |f| %>
  
  <% if @dish %> 

  
  <%= hidden_field_tag(:dish_id, @dish.id) %>
  <% end %>



  <% unless @dish %>
  <div class="control-group">
    <%= f.label :dish_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :dish_id, :class => 'number_field' %>
    </div>
  </div>
  <%end%>



<div class="control-group">
<label class="control-label" for="availability_day">Day Available</label>
<div class="controls">
<select name="day" size="7" multiple>
	<option value="Sunday">Sunday
	<option value="Monday">Monday
	<option value="Tuesday">Tuesday
	<option value="Wednesday">Wednesday
	<option value="Thursday">Thursday				
	<option value="Friday">Friday
	<option value="Saturday">Saturday
</select>
</div>
</div>

  <div class="control-group">
    <%= f.label :starts_on, :class => 'control-label' %>
    <div class="controls">
      <%= f.time_select :starts_on, 
		:combined => true,
		:minute_interval => 15,
		:time_separator => "",
		:start_hour => 17,
		:default => Time.new(2013,4, 7, 18,30), 
		:class => 'date_select', 
		:ampm => true 
	  %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :expires_on, :class => 'control-label' %>
    <div class="controls">
      <%= f.time_select :expires_on, 
						:combined => true,
						:minute_interval => 15,
						:start_hour => 17,
						:time_separator => "",
						:default => Time.new(2013,4,7,20,30), 
						:class => 'date_select', 
						:ampm => true 
	  %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label "Number of servings", :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :initial_amount, :value => 5, 
						 :class => 'number_field' %>
    </div>
  </div>



  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                availabilities_path, :class => 'btn' %>
  </div>
<% end %>

app/views/availabilities/edit.html.erb
<%- model_class = Availability -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/availabilities/index.html.erb
<%- model_class = Availability -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:initial_amount) %></th>
      <th><%= model_class.human_attribute_name(:remaining_amount) %></th>
      <th><%= model_class.human_attribute_name(:expires_on) %></th>
      <th><%= model_class.human_attribute_name(:dish_id) %></th>
      <th><%= model_class.human_attribute_name(:starts_on) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @availabilities.each do |availability| %>
      <tr>
        <td><%= link_to availability.id, availability_path(availability) %></td>
        <td><%= availability.initial_amount %></td>
        <td><%= availability.remaining_amount %></td>
        <td><%= availability.expires_on %></td>
        <td><%= availability.dish_id %></td>
        <td><%= availability.starts_on %></td>
        <td><%=l availability.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_availability_path(availability), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      availability_path(availability),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_availability_path,
            :class => 'btn btn-primary' %>

app/views/availabilities/new.html.erb
<%- model_class = Availability -%>
<div class="page-header">
	<h1>Selling <%= @dish.name %> </h1>
</div>
<%= render :partial => 'form' %>

app/views/availabilities/show.html.erb
<%- model_class = Availability -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:initial_amount) %>:</strong></dt>
  <dd><%= @availability.initial_amount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:remaining_amount) %>:</strong></dt>
  <dd><%= @availability.remaining_amount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:expires_on) %>:</strong></dt>
  <dd><%= @availability.expires_on %></dd>
  <dt><strong><%= model_class.human_attribute_name(:dish_id) %>:</strong></dt>
  <dd><%= @availability.dish_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:starts_on) %>:</strong></dt>
  <dd><%= @availability.starts_on %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              availabilities_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_availability_path(@availability), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              availability_path(@availability),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>