config/routes.rb
FreshpicksApi::Application.routes.draw do
  
  match 'today' => 'availabilities#today'
  match '', :to => redirect('/index.html'), :as => :root
  match '/', :to => redirect('/index.html'), :as => :root

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout
  match "/dish/:dish_id/availabilities/new" => "availabilities#new", :as => :newavailability

  resources :availabilities
  resources :dishes
  resources :chefs

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fresh Picks</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">Some Store</a>

        <div class="btn-group pull-right authmenu">
          <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
            <% if current_user %>
              <i class="icon-user"></i> <%= current_user.name %>
            <% else %>
              <i class="icon-user"></i> Sign in
            <% end  %>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">

            <% if current_user %>
              <li><a href="#">Profile</a></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", signout_path %></li>
            <% else %>
              <li><%= link_to "Twitter", "/auth/twitter" %></li>
              <li><%= link_to "Facebook", "/auth/facebook" %></li>
            <% end %>

          </ul>
        </div>

        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Other Chefs", chefs_path %></li>
            <li><%= link_to "My Dishes", dishes_path %></li>
            <li><%= link_to "Availability", availabilities_path%></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="span12 noticespanel">
        <%if notice %>
            <div class="alert">
              <button class="close" data-dismiss="alert">×</button>
              <%= notice %>
            </div>
        <%end%>
        <%if flash[:error] %>
            <div class="alert alert-error">
              <button class="close" data-dismiss="alert">×</button>
              <%= flash[:error] %>
            </div>
        <%end%>
      </div>

      <div class="span12 maincontent"><%= yield %></div>
      
    </div>
  </div>
</body>
</html>

app/views/layouts/clear_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fresh Picks</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <link rel="stylesheet"  href="/css/style.css" type="text/css" media="all">
  <%= csrf_meta_tags %>
</head>
<body>
 <div class="container">
    <div class="row">
      <div class="span12 noticespanel">
        <%if notice %>
            <div class="alert">
              <button class="close" data-dismiss="alert">×</button>
              <%= notice %>
            </div>
        <%end%>
        <%if flash[:error] %>
            <div class="alert alert-error">
              <button class="close" data-dismiss="alert">×</button>
              <%= flash[:error] %>
            </div>
        <%end%>
      </div>

      
    </div>
  </div>

  <%= yield %>
      
</body>
</html>